name: development

on: [ push, pull_request ]

permissions:
  contents: read
  pull-requests: read
  checks: write

env:
  GO_VERSION: 1.22

jobs:
  maintenance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: golangci/golangci-lint-action@v6
        name: install golangci
        with:
          version: latest
          args: --help

      - name: lint
        run: make lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: install dependencies
        run: go install .

      - name: build kube2kafka
        run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: install dependencies
        run: go install .

      - name: install ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo

      - name: test
        run: make test
